### ISSUE TITLE
Panel is too small

### ISSUE THREAD

**Issue by henno** [avm99963/translateselectedtext#7]
1. From options, set translation to open in panel.
2. Try it.

Expected result:
I can see the translation in the panel.

What happens instead:
I can't see the top part of the Google Translate web page in panel. And no translation. I must manually scroll the scrollbars to see the translation to see the translation.

Screenshot:
![image](https://cloud.githubusercontent.com/assets/92807/16667479/54e84750-4495-11e6-821d-e2cfb8412257.png)

**Comment by henno** [comment]
I believe [background.js, line 32](https://github.com/avm99963/translateselectedtext/blob/master/src/background.js#L32) is responsible for the width and height of this window. Could you adjust them, so that the panel would not be so small, please?

**Comment by avm99963** [comment]
Hi @henno !

I'm aware of this problem since the first day I added the panels option to the extension :/

You can see in the line you linked the width is set to 1000px, which is a lot, but the panels are not that large (maybe because of some limitation in the width).

Anyways, I've found the following question in StackOverflow which might help me resolve this issue: http://stackoverflow.com/questions/30013748/chrome-extension-unable-to-resize-panel

I'll give this a try and I'll let you know if I achieve something.

Thanks for reporting! ;)

**Comment by avm99963** [comment]
Panels have been deprecated in Chrome a while ago\[1\] so this issue no longer makes sense. The feature to open the translation in panels is still in the extension, but it creates a new window instead of a panel.

Therefore, I'm closing this issue as "wontfix" because it can't be fixed.

\[1\]: https://bugs.chromium.org/p/chromium/issues/detail?id=467808#c107
